name: deploy-to-pi
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github_actions
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: replace
      - name: Pull
        run: ssh ${{ secrets.IP_ADDRESS }} "cd /home/pi/app && /usr/bin/git pull origin"
      
