name: deploy-to-pi
on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Tailscale in GitHub Actions
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY
          tailscale status

      - name: Debug Tailscale Connection
        run: |
          tailscale status
          tailscale ip -4
          ping -c 4 ${{ secrets.TAILSCALE_IP }}

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H pi@100.105.83.97 >> ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        env:
          IP_ADDRESS: ${{ secrets.TAILSCALE_IP }}
        run: |
          ssh-keyscan -H $IP_ADDRESS >> ~/.ssh/known_hosts
          rsync -avz . pi@$IP_ADDRESS:/home/pi/app
          ssh pi@$IP_ADDRESS 'bash /home/pi/app/deploy.sh'
      
