name: deploy-to-pi
on:
  push:
    branches:
       - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Tailscale in GitHub Actions
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
      - name: Debug Network & SSH
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=$TAILSCALE_AUTH_KEY
          tailscale status

      - name: Debug Network & SSH
        run: |
          echo "Checking if GitHub Actions can see the Pi..."
          ping -c 4 ${{ secrets.TAILSCALE_PI_IP }}

          echo "Checking available network interfaces..."
          ip addr show

          echo "Checking if SSH is installed in GitHub Actions..."
          which ssh || echo "SSH NOT FOUND"

          echo "Manually testing SSH connection..."
          ssh -v -o StrictHostKeyChecking=no pi@${{ secrets.TAILSCALE_PI_IP }} "echo SSH connection successful"


      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H pi@100.105.83.97 >> ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        run: |
          ssh-keyscan -H pi@100.105.83.97 >> ~/.ssh/known_hosts
          rsync -avz . pi@100.105.83.97:/home/pi/app
          ssh -o StrictHostKeyChecking=no pi@100.105.83.97 'bash /home/pi/app/deploy.sh'
      
